name: Test
on: [push]

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:8.0.20
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_USER: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0.2
      - name: Install yarn and nodejs
        run: sudo apt-get install -y yarn nodejs && yarn install --check-files
      - name: Install dependencies
        run: bundle install
      - name: Set up DB
        run: bundle exec rails db:create db:migrate
